# Dataset Information

Additional Information

Vina conducted a comparison test of her rule-based system, BEAGLE, the nearest-neighbor algorithm, and discriminant analysis.  BEAGLE is a product available through VRS Consulting, Inc.; 4676 Admiralty Way, Suite 206; Marina Del Ray, CA 90292 (213) 827-7890 and FAX: -3189. In determining whether the glass was a type of "float" glass or not, the following results were obtained (# incorrect answers):

Type of Sample  -- Beagle -- NN -- DA
Windows that were float processed (87)  -- 10 -- 12 -- 21
Windows that were not:            (76) -- 19 -- 16 -- 22

The study of classification of types of glass was motivated by criminological investigation.  At the scene of the crime, the glass left can be used as evidence...if it is correctly identified!

Has Missing Values?

No

In [2]:
from ucimlrepo import fetch_ucirepo 
import pandas as pd
  
# fetch dataset 
glass_identification = fetch_ucirepo(id=42) 
  
# data (as pandas dataframes) 
X = glass_identification.data.features 
y = glass_identification.data.targets 
  
# metadata 
print(glass_identification.metadata) 
  
# variable information 
print(glass_identification.variables) 

display(X)
display(y)

{'uci_id': 42, 'name': 'Glass Identification', 'repository_url': 'https://archive.ics.uci.edu/dataset/42/glass+identification', 'data_url': 'https://archive.ics.uci.edu/static/public/42/data.csv', 'abstract': 'From USA Forensic Science Service; 6 types of glass; defined in terms of their oxide content (i.e. Na, Fe, K, etc)', 'area': 'Physics and Chemistry', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 214, 'num_features': 9, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['Type_of_glass'], 'index_col': ['Id_number'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1987, 'last_updated': 'Thu Aug 10 2023', 'dataset_doi': '10.24432/C5WW2P', 'creators': ['B. German'], 'intro_paper': None, 'additional_info': {'summary': 'Vina conducted a comparison test of her rule-based system, BEAGLE, the nearest-neighbor algorithm, and discriminant analysis.  BEAGLE is a product available through VRS Consulting, Inc.; 4676 Admiralty Way, Suite 206; Marina Del Ray, CA 90292 (213) 827-7890 and FAX: -3189. In determining whether the glass was a type of "float" glass or not, the following results were obtained (# incorrect answers):\r\n\r\nType of Sample  -- Beagle -- NN -- DA\r\nWindows that were float processed (87)  -- 10 -- 12 -- 21\r\nWindows that were not:            (76) -- 19 -- 16 -- 22\r\n\r\nThe study of classification of types of glass was motivated by criminological investigation.  At the scene of the crime, the glass left can be used as evidence...if it is correctly identified!', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': '1. Id number: 1 to 214\r\n2. RI: refractive index\r\n3. Na: Sodium (unit measurement: weight percent in corresponding oxide, as are attributes 4-10)\r\n4. Mg: Magnesium\r\n5. Al: Aluminum\r\n6. Si: Silicon\r\n7. K: Potassium\r\n8. Ca: Calcium\r\n9. Ba: Barium\r\n10. Fe: Iron\r\n11. Type of glass: (class attribute)\r\n     -- 1 building_windows_float_processed\r\n     -- 2 building_windows_non_float_processed\r\n     -- 3 vehicle_windows_float_processed\r\n     -- 4 vehicle_windows_non_float_processed (none in this database)\r\n     -- 5 containers\r\n     -- 6 tableware\r\n     -- 7 headlamps', 'citation': None}}
             name     role         type demographic       description  \
0       Id_number       ID      Integer        None               NaN
1              RI  Feature   Continuous        None  refractive index
2              Na  Feature   Continuous        None            Sodium
3              Mg  Feature   Continuous        None         Magnesium
4              Al  Feature   Continuous        None          Aluminum
5              Si  Feature   Continuous        None           Silicon
6               K  Feature   Continuous        None         Potassium
7              Ca  Feature   Continuous        None           Calcium
8              Ba  Feature   Continuous        None            Barium
9              Fe  Feature   Continuous        None              Iron
10  Type_of_glass   Target  Categorical        None               NaN

                                    units missing_values
0                                     NaN             no
1                                     NaN             no
2   weight percent in corresponding oxide             no
3   weight percent in corresponding oxide             no
4   weight percent in corresponding oxide             no
5   weight percent in corresponding oxide             no
6   weight percent in corresponding oxide             no
7   weight percent in corresponding oxide             no
8   weight percent in corresponding oxide             no
9   weight percent in corresponding oxide             no
10                                    NaN             no

          RI     Na    Mg    Al     Si     K    Ca    Ba   Fe
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0
..       ...    ...   ...   ...    ...   ...   ...   ...  ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0

[214 rows x 9 columns]

     Type_of_glass
0                1
1                1
2                1
3                1
4                1
..             ...
209              7
210              7
211              7
212              7
213              7

[214 rows x 1 columns]